//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignalR_POC.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserFBLike
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> PostId { get; set; }
        public Nullable<bool> LikeDislike { get; set; }
        public string User { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
    }
}
